language: ruby
rvm:
  - 2.6.3

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

services:
  - docker
  - redis-server
  
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate

before_install:
  - rvm @default,@global do gem uninstall bundler -x
  - gem install bundler -v 2.0.1
  - bundle --version
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

cache:
  bundler: true

include:
  - stage: Test
    php: 7.2
    env: DB=sqlsrv
    sudo: required
    services:
      - docker
    before_script:
      - bash ./travis/install-sqlsrv-dependencies.sh
      - bash ./travis/install-mssql-sqlsrv.sh
      - bash ./travis/install-mssql.sh
  - stage: Test
    php: 7.3
    env: DB=sqlsrv COVERAGE=yes
    sudo: required
    services:
      - docker
    before_script:
      - bash ./travis/install-sqlsrv-dependencies.sh
      - bash ./travis/install-mssql-sqlsrv.sh
      - bash ./travis/install-mssql.sh
  - stage: Test
    php: 7.4snapshot
    env: DB=sqlsrv
    sudo: required
    services:
      - docker
    before_script:
      - bash ./travis/install-sqlsrv-dependencies.sh
      - bash ./travis/install-mssql-sqlsrv.sh
      - bash ./travis/install-mssql.sh

