language: ruby
rvm:
  - 2.6.3

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

services:
  - docker
  - redis-server

before_install:
  - sudo apt-get install wget
  - sudo apt-get install build-essential
  - sudo apt-get install libc6-dev
  - wget http://www.freetds.org/files/stable/freetds-1.00.21.tar.gz
  - tar -xzf freetds-1.00.21.tar.gz
  - cd freetds-1.00.21
  - sudo ./configure --prefix=/usr/local --with-tdsver=7.3
  - sudo make
  - sudo make install
  - gem install tiny_tds -v '2.0.0'
  - docker pull mcr.microsoft.com/mssql/server
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=wbooks-api' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
  - docker ps -a
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system
  - gem install bundler
  - bundler update --bundler

  
before_script:
#  - cp config/database.travis.yml config/database.yml
#  - psql -c "CREATE USER \"wbooks-api\" WITH PASSWORD 'wbooks-api';" -U postgres
#  - psql -c "DROP DATABASE IF EXISTS \"wbooks-api_test\";" -U postgres
#  - psql -c "CREATE DATABASE \"wbooks-api_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:create
#  - bundle exec rake db:migrate

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

cache:
  bundler: true
