language: ruby
rvm:
  - 2.6.3

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

services:
  - redis-server
  - docker
  
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:migrate

before_install:
  - docker pull mcr.microsoft.com/mssql/server
  - docker run -d -e 'SA_PASSWORD=wbooks-api' -p 127.0.0.1:80:1433 mcr.microsoft.com/mssql/server /bin/sh
  - docker ps -a
  - docker run mcr.microsoft.com/mssql/server /bin/sh
  - rvm @default,@global do gem uninstall bundler -x
  - gem install bundler -v 2.0.1
  - bundle --version
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

script:
  - bundle exec rails test
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

cache:
  bundler: true

